### PR TITLE
Bumping version to 1.2.4

### PR DESCRIPTION
**Pull request by marceloboeira**

### CODE REVIEW

**Comment by cassiomarques** [comment]
@marceloboeira 1.2.4 is already the current version: https://rubygems.org/gems/enumerate_it/versions/1.2.4

**Comment by marceloboeira** [comment]
Well, the code shows otherwise, shouldn't the gem version be 1.2.4 at the module?

https://github.com/cassiomarques/enumerate_it/blob/49c163c7ccf46c0f49f8d8cb185a839b787a87db/lib/enumerate_it/version.rb#L2

**Comment by cassiomarques** [comment]
Sorry, as I said in the PR comment, it looks like I forgot to push the changes to the code, however the new version got published. This is why you're able to install it locally. The fact that it's out dated on Github shouldn't cause any problem.

**Comment by marceloboeira** [comment]
@cassiomarques you can change a tag revision at github, but I believe that wouldn't get any effect at the published version. :disappointed:

**Comment by cassiomarques** [comment]
Yup, that's true.

We are currently using enumerate_it 1.2.4 in one of our projects, with the build on CircleCI, all working fine. For me it looks like a temporary problem with your CI server.

**Comment by cassiomarques** [comment]
Closing, since the problem was resolved in https://github.com/cassiomarques/enumerate_it/issues/45

**Pull request closed without merging**
